keys:
  - &zroot age1fju47f2mtxvp0e7ty9arxvj3r5g74wquqm6ta2nmdt53j0kzqegq4v8rrh
  - &thinkpad age19y20q5xtde7m6hll73efnapefwqwazfq6lm6zqf89c49wpj4ug6s3jsg4e
  - &rpi516g-k age1ds0335ylww0stvwlm4fdwtkf95zpte7vjr57cmasvcthjkff3u9qgt4eaz
creation_rules:
  - path_regex: ^secrets\.yaml$
    key_groups:
    - age:
      - *zroot
      - *thinkpad
      - *rpi516g-k
